name: Docker-Image CI

on:
  push:
    branches:
      - master

env:
  REPO_URL: hkccr.ccs.tencentyun.com
  TCR_IMAGE_URL: hkccr.ccs.tencentyun.com/sxu-oj/judger

jobs:
  setup-build-publish-deploy:
    name: Setup, Test, Build, Publish, and Deploy
    runs-on: ubuntu-18.04
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup
      - name: Setup
        run: |
          sudo apt-get install -y protobuf-compiler libprotobuf-dev libseccomp-dev
          
      # Test
      - name: Test
        run: |
          make test

      # Build
      - name: Build Docker image
        run: |
          docker build -t ${TCR_IMAGE_URL}:latest .
          
      # Login
      - name: Login TCR Registry
        run: |
          docker login ${REPO_URL} --username=${{ secrets.REPO_USERNAME }} --password='${{ secrets.REPO_PASSWORD  }}'
      
      # Push the Docker image to TCR Registry
      - name: Publish
        run: |
          docker push ${TCR_IMAGE_URL}:latest 
